// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function AddFolder(arg1:string):Promise<void>;

export function AddIgnoredFolder(arg1:string):Promise<void>;

export function DetectMissingVectorBlobs():Promise<boolean>;

export function EmitEvent(arg1:string):Promise<void>;

export function GetDebugStats():Promise<Record<string, any>>;

export function GetEmbedderStats():Promise<app.EmbedderStatsDTO>;

export function GetFilePreview(arg1:string):Promise<string>;

export function GetFolders():Promise<Array<string>>;

export function GetHasGeminiKey():Promise<boolean>;

export function GetHotkeyString():Promise<string>;

export function GetIgnoredFolders():Promise<Array<string>>;

export function GetIndexFailures():Promise<Array<app.IndexFailureDTO>>;

export function GetIndexStatus():Promise<app.IndexStatusDTO>;

export function GetIndexingSettings():Promise<app.IndexingSettingsDTO>;

export function GetNLQueryEnabled():Promise<boolean>;

export function GetOnboarded():Promise<boolean>;

export function GetPreviewClipPath(arg1:string,arg2:number):Promise<string>;

export function GetSetting(arg1:string):Promise<string>;

export function HideWindow():Promise<void>;

export function MarkOnboarded():Promise<void>;

export function NeedsReindex():Promise<boolean>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function ParseQuery(arg1:string):Promise<app.ParseQueryResult>;

export function PauseIndexing():Promise<void>;

export function PickAndAddFolder():Promise<string>;

export function PreEmbedQuery(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function ReindexFolder(arg1:string):Promise<void>;

export function ReindexNow():Promise<void>;

export function RemoveFolder(arg1:string,arg2:boolean):Promise<void>;

export function RemoveIgnoredFolder(arg1:string):Promise<void>;

export function ResumeIndexing():Promise<void>;

export function Search(arg1:string):Promise<Array<app.SearchResultDTO>>;

export function SearchWithFilters(arg1:string,arg2:string,arg3:Array<string>):Promise<app.SearchWithFiltersResult>;

export function SetBaseContext(arg1:context.Context):Promise<void>;

export function SetGeminiAPIKey(arg1:string):Promise<void>;

export function SetIndexingSettings(arg1:number,arg2:number):Promise<void>;

export function SetNLQueryEnabled(arg1:boolean):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function ToggleWindow():Promise<void>;
