// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder(arg1) {
  return window['go']['app']['App']['AddFolder'](arg1);
}

export function AddIgnoredFolder(arg1) {
  return window['go']['app']['App']['AddIgnoredFolder'](arg1);
}

export function DetectMissingVectorBlobs() {
  return window['go']['app']['App']['DetectMissingVectorBlobs']();
}

export function EmitEvent(arg1) {
  return window['go']['app']['App']['EmitEvent'](arg1);
}

export function GetDebugStats() {
  return window['go']['app']['App']['GetDebugStats']();
}

export function GetFilePreview(arg1) {
  return window['go']['app']['App']['GetFilePreview'](arg1);
}

export function GetFolders() {
  return window['go']['app']['App']['GetFolders']();
}

export function GetHasGeminiKey() {
  return window['go']['app']['App']['GetHasGeminiKey']();
}

export function GetHotkeyString() {
  return window['go']['app']['App']['GetHotkeyString']();
}

export function GetIgnoredFolders() {
  return window['go']['app']['App']['GetIgnoredFolders']();
}

export function GetIndexFailures() {
  return window['go']['app']['App']['GetIndexFailures']();
}

export function GetIndexStatus() {
  return window['go']['app']['App']['GetIndexStatus']();
}

export function GetNLQueryEnabled() {
  return window['go']['app']['App']['GetNLQueryEnabled']();
}

export function GetOnboarded() {
  return window['go']['app']['App']['GetOnboarded']();
}

export function GetPreviewClipPath(arg1, arg2) {
  return window['go']['app']['App']['GetPreviewClipPath'](arg1, arg2);
}

export function GetSetting(arg1) {
  return window['go']['app']['App']['GetSetting'](arg1);
}

export function HideWindow() {
  return window['go']['app']['App']['HideWindow']();
}

export function MarkOnboarded() {
  return window['go']['app']['App']['MarkOnboarded']();
}

export function NeedsReindex() {
  return window['go']['app']['App']['NeedsReindex']();
}

export function OpenFile(arg1) {
  return window['go']['app']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['app']['App']['OpenFolder'](arg1);
}

export function ParseQuery(arg1) {
  return window['go']['app']['App']['ParseQuery'](arg1);
}

export function PauseIndexing() {
  return window['go']['app']['App']['PauseIndexing']();
}

export function PickAndAddFolder() {
  return window['go']['app']['App']['PickAndAddFolder']();
}

export function PreEmbedQuery(arg1) {
  return window['go']['app']['App']['PreEmbedQuery'](arg1);
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function ReindexFolder(arg1) {
  return window['go']['app']['App']['ReindexFolder'](arg1);
}

export function ReindexNow() {
  return window['go']['app']['App']['ReindexNow']();
}

export function RemoveFolder(arg1, arg2) {
  return window['go']['app']['App']['RemoveFolder'](arg1, arg2);
}

export function RemoveIgnoredFolder(arg1) {
  return window['go']['app']['App']['RemoveIgnoredFolder'](arg1);
}

export function ResumeIndexing() {
  return window['go']['app']['App']['ResumeIndexing']();
}

export function Search(arg1) {
  return window['go']['app']['App']['Search'](arg1);
}

export function SearchWithFilters(arg1, arg2, arg3) {
  return window['go']['app']['App']['SearchWithFilters'](arg1, arg2, arg3);
}

export function SetBaseContext(arg1) {
  return window['go']['app']['App']['SetBaseContext'](arg1);
}

export function SetGeminiAPIKey(arg1) {
  return window['go']['app']['App']['SetGeminiAPIKey'](arg1);
}

export function SetNLQueryEnabled(arg1) {
  return window['go']['app']['App']['SetNLQueryEnabled'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['app']['App']['SetSetting'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['app']['App']['ShowWindow']();
}

export function ToggleWindow() {
  return window['go']['app']['App']['ToggleWindow']();
}
