// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder(arg1) {
  return window['go']['main']['App']['AddFolder'](arg1);
}

export function AddIgnoredFolder(arg1) {
  return window['go']['main']['App']['AddIgnoredFolder'](arg1);
}

export function EmitEvent(arg1) {
  return window['go']['main']['App']['EmitEvent'](arg1);
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetIgnoredFolders() {
  return window['go']['main']['App']['GetIgnoredFolders']();
}

export function GetIndexStatus() {
  return window['go']['main']['App']['GetIndexStatus']();
}

export function GetPreviewClipPath(arg1, arg2) {
  return window['go']['main']['App']['GetPreviewClipPath'](arg1, arg2);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PauseIndexing() {
  return window['go']['main']['App']['PauseIndexing']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReindexNow() {
  return window['go']['main']['App']['ReindexNow']();
}

export function RemoveFolder(arg1, arg2) {
  return window['go']['main']['App']['RemoveFolder'](arg1, arg2);
}

export function RemoveIgnoredFolder(arg1) {
  return window['go']['main']['App']['RemoveIgnoredFolder'](arg1);
}

export function ResumeIndexing() {
  return window['go']['main']['App']['ResumeIndexing']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}
