// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFolder(arg1:string):Promise<void>;

export function AddIgnoredFolder(arg1:string):Promise<void>;

export function EmitEvent(arg1:string):Promise<void>;

export function GetFilePreview(arg1:string):Promise<string>;

export function GetFolders():Promise<Array<string>>;

export function GetHasGeminiKey():Promise<boolean>;

export function GetHotkeyString():Promise<string>;

export function GetOnboarded():Promise<boolean>;

export function MarkOnboarded():Promise<void>;

export function GetIgnoredFolders():Promise<Array<string>>;

export function GetIndexStatus():Promise<main.IndexStatusDTO>;

export function GetPreviewClipPath(arg1:string,arg2:number):Promise<string>;

export function GetSetting(arg1:string):Promise<string>;

export function HideWindow():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function PauseIndexing():Promise<void>;

export function PreEmbedQuery(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function ReindexFolder(arg1: string): Promise<void>;

export function ReindexNow():Promise<void>;

export function RemoveFolder(arg1:string,arg2:boolean):Promise<void>;

export function RemoveIgnoredFolder(arg1:string):Promise<void>;

export function ResumeIndexing():Promise<void>;

export function Search(arg1:string):Promise<Array<main.SearchResultDTO>>;

export function SetGeminiAPIKey(arg1:string):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function ToggleWindow():Promise<void>;
