// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFolder(arg1:string):Promise<void>;

export function GetFolders():Promise<Array<string>>;

export function GetIndexStatus():Promise<main.IndexStatusDTO>;

export function GetPreviewClipPath(arg1:string,arg2:number):Promise<string>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function PauseIndexing():Promise<void>;

export function ReindexNow():Promise<void>;

export function ResumeIndexing():Promise<void>;

export function Search(arg1:string):Promise<Array<main.SearchResultDTO>>;
